### PR TITLE
Add simple targets

### PR DESCRIPTION
**Pull request by jasmin-j**
Add simple targets configure, distclean, menuconfig and help.

Signed-off-by: Jasmin Jessich jasmin@anw.at

### CODE REVIEW

**Comment by jasmin-j** [comment]
Pull request #14 must be applied before this one.

**Comment by jasmin-j** [comment]
This pull request is based on pull request #14.

**Comment by jasmin-j** [comment]
I changed the commit with your comments and made some improvements.

Do you know why your comments are no longer available here on this page?

> I would prefer CONFIGURATION_PATH instead of CFG_PATH (or at least CONFIG_PATH).

I choose  CONFIG_PATH, because you have to enter it with the keyboard. That was the reason to use a very short name (CFG_PATH) before. I even would prefer CFG_P, but you like longer names ;)

> Could the same be achieved with a construct like this:
> cat << EOL
> <the help texts with indentions and so on>
> EOL

No, because you can't write here documents in makefiles. But I used another trick which allows to write the whole help text as block and to circumvent the newline interpretation of make.

**Comment by KamilSzczygiel** [comment]
Merged manually with minor changes. Thanks!

I had to make help text lines 1-character shorter, as on Windows the default shell size seems to be smaller than on Linux, and there were excessive empty lines.

> Do you know why your comments are no longer available here on this page?

I also don't like that they disappear... The comments are for specific commit hash in you repository. When you do anything with your branch (rebase, modify, amend, change commit message, ...) the commit hashes change, so you don't see the comments anymore... The only option to reach them again is via the "old" commit hash (because the commits are in you repository, but they are not visible "normally") - you should have that value (and the link) in the e-mail you got from GitHub.

**Pull request closed without merging**
