### PR TITLE
NUCLEO-L073RZ board

### PR DESCRIPTION
**Pull request by CezaryGapinski**
Support for NUCLEO-L073RZ board

### CODE REVIEW

**Comment by CezaryGapinski** [comment]
> I would fix that myself, but I cannot test the resulting file, so I have to ask you (;

I made a mess, so I have to clean this up ;).

Ok, I guess the signals are enabled now, I changed HSE to bypass  8MHz + PLL (MUL 12, DIV 3), APB1 and 2 changed to DIV 1.
Test passed correctly, blinking time seems to be correct.

**Comment by FreddieChopin** [comment]
Huge thanks for your contributions! Merged with a very minor cleanup - kconfig is a bit stupid sometimes and to make the file "absolutely final" you have to run `make olddefconfig` on them after such edit. When some options are added/changed/removed/... I run this command twice. To simplify that you can just do:

`./scripts/forAllConfigurations.sh "make olddefconfig"`

But this is not a problem, I can safely do that myself.

**Comment by FreddieChopin** [comment]
BTW - any more plans? (;

**Comment by CezaryGapinski** [comment]
Yes, I working on driver for ssd1289 display for HY-Mini board. For now I have just a "concept". Actually I have some code but I think is not ready to push it to public repo ;).

**Pull request closed without merging**
