### PR TITLE
Restructure makefile

### PR DESCRIPTION
**Pull request by jasmin-j**
Added again some makefile enhancements.

Signed-off-by: Jasmin Jessich jasmin@anw.at

### CODE REVIEW

**Comment by jasmin-j** [comment]
I plan to add more beautifying, if you like it.
- In my Makefiles I try to align the "=" of the variable definitions of blocks. Yes/No?
```
AS      = $(CONFIG_TOOLCHAIN_PREFIX)gcc
CC      = $(CONFIG_TOOLCHAIN_PREFIX)gcc
CXX     = $(CONFIG_TOOLCHAIN_PREFIX)g++
AR      = $(CONFIG_TOOLCHAIN_PREFIX)ar
LD      = $(CONFIG_TOOLCHAIN_PREFIX)g++
OBJCOPY = $(CONFIG_TOOLCHAIN_PREFIX)objcopy
OBJDUMP = $(CONFIG_TOOLCHAIN_PREFIX)objdump
SIZE    = $(CONFIG_TOOLCHAIN_PREFIX)size

RM = rm -f
```
- I use mostly ":=" instead of "=", because it speeds up make processing as the variable is not always
  expanded recursively when it is used. An yes, it is not always possible, but with most variables it is. Yes/No?
```
AS      := $(CONFIG_TOOLCHAIN_PREFIX)gcc
CC      := $(CONFIG_TOOLCHAIN_PREFIX)gcc
CXX     := $(CONFIG_TOOLCHAIN_PREFIX)g++
AR      := $(CONFIG_TOOLCHAIN_PREFIX)ar
LD      := $(CONFIG_TOOLCHAIN_PREFIX)g++
OBJCOPY := $(CONFIG_TOOLCHAIN_PREFIX)objcopy
OBJDUMP := $(CONFIG_TOOLCHAIN_PREFIX)objdump
SIZE    := $(CONFIG_TOOLCHAIN_PREFIX)size

RM := rm -f
```

**Comment by KamilSzczygiel** [comment]
UNQUOTE_D commit:

Why is the macro called "UNQUOTE_D"? What does the "_D" stand for? Maybe just "UNQUOTE" or "UNQUOTE_STRING"?

Indention commit:

Some lines use spaces, some use tabs. I try to always use tabs, but in Makefile these are problematic and should be limited only to rules, so I thing that the indention you changed should all use spaces (4 spaces for 1 "level").

Would it be possible to indent the DIRECTORY_DEPENDENCY and MAKE_DIRECTORY macros with spaces somehow?

PRETTY_PRINT commit:

1. You use DO_PRINT, but I don't see it anywhere.
2. I don't think this improves the situation much. Now if a "prefix" longer than 3 characters will be used in future we'll have to modify all calls anyway, so how is that different from what we have now? I think this is over-complicating.

OUTPUT commit:

The only thing I can agree on is a suffix - the OUTPUT _MUST_ be "output/", at least to make "make clean" and distclean script work fine. So I suggest to add optional OUTPUT_SUFFIX (which could be overridden by environment), by default empty, and the full output path would be $(OUTPUT)$(OUTPUT_SUFFIX).

> In my Makefiles I try to align the "=" of the variable definitions of blocks. Yes/No?

No (; This is a 100% subjective thing - for me it serves no purpose, when you add new line to a block you would sometimes be forced to reformat the whole block just to have everything aligned again.

> I use mostly ":=" instead of "=", because it speeds up make processing as the variable is not always expanded recursively when it is used. An yes, it is not always possible, but with most variables it is. Yes/No?

Yes, but I don't think we should be really concerned about make's processing speed - the build is still not that complicated so it makes no difference if processing takes 0.1s or 0.2s. On my PC the execution starts immediately. This particular change proposal is OK and I'm fine with that. I'm writing this only for future, as I wouldn't like to introduce any changes that would make the build files more complicated for the sole purpose of make's processing speed.

**Comment by jasmin-j** [comment]
#### UNQUOTE_D commit:
> Why is the macro called "UNQUOTE_D"? What does the "_D" stand for? Maybe just "UNQUOTE"
> or "UNQUOTE_STRING"?

The "_D" stands for "Double" which means the " sign.
When ever we need to remove the ' sign, we can call it "UNQUOTE_S". "_S" for single.
But if you prefer to remove the "_D" it is OK for now.


#### Indention commit:
> Some lines use spaces, some use tabs.

Sorry, this was VI with the ">" intent function. It should have been "    ".

> Would it be possible to indent the DIRECTORY_DEPENDENCY and MAKE_DIRECTORY macros
> with spaces somehow?

No, because this defines rules and the target of a rule __have__ to start in column 1.


#### PRETTY_PRINT commit:
> You use DO_PRINT, but I don't see it anywhere.

It is just above inside the VERBOSE if. In make every "=" definition is a macro which can be called. This is no side effect, but intended. Moreover, it helps to keep makefiles smaller.
The "define" keyword is to define a multi-line macro which contains "\n". You can use it to define simple macros too, but this really depend on personal taste and readability.

> I don't think this improves the situation much. Now if a "prefix" longer than 3 characters will be
> used in future we'll have to modify all calls anyway, so how is that different from what we have
> now? I think this is over-complicating.

It was the first step to have only __one__ print macro who really does the job. You can say this is a printing subroutine. I aligned the texts to keep the current behaviour. In the long run, I planned to use "prinf" in DO_PRINT. But currently I have no Windows with MSYS arround to test, if printf is supported by the MSYS installation. With printf we can then add "\t".
It is always a good practice to use subroutines for common tasks. You do this in your code, too. The same is true for makefiles ;)
We even don't need to change the aligned parameter 1 in all of the PRETTY_PRINT calls, as there is the $(strip ..) function to remove any surrounding " ". But when I add "printf", I will definitely remove the alignment spaces.

Please can you test in a MSYS shell if "printf" is available.


#### OUTPUT commit:
> So I suggest to add optional OUTPUT_SUFFIX (which could be overridden by environment), by
> default empty, and the full output path would be $(OUTPUT)$(OUTPUT_SUFFIX).

OK, I agree. I was really late this night and when I saw distclean.sh using "output/", I already committed my change.
I will add this "OUTPUT_SUFFIX" with the same macros to ensure it has a trailing '/'.


#### Questions:
> ... when you add new line to a block you would sometimes be forced to reformat the whole block
> just to have everything aligned again.

I know this from my company. There we have the rule to align even variable definitions at the beginning of a C function. So we use more spaces than required to be open for such a change, but sometimes I need to extend the spaces in all lines. On the other hand it is more readable and that's the reason why the company forces this rule.

> Yes, but I don't think we should be really concerned about make's processing speed

I needed to write anything why I would like to change it, to be honest. Most of the people using make don't know the difference, even the don't know ":=". For me it is more logical to use ":=", because it behaves more like a variable in C. There are cases when you need the '=', but mostly when you write macros and generic makefiles which define generic variables to be used by rules to extend them later by predefined variables, currently not defined.

There is one special thing if you define a variable with ":=" and add later others with "+=". Then the "+=" behaves like ":=". This might be an issue for CFLAGS and similar variables. I would never define those with ":=". But for RM, AS, CC this is required.
Additionally I would define CONFIG_TOOLCHAIN_PREFIX with "?=" to allow overriding it in the environment, even it is configurable in the configuration. This allows reusing your predefined configurations with another compiler (e.g.: arm-distortos-eabi), without changing them. This might be mostly help __us__ to introduce another toolchain, but in general I like to have makefiles flexible.
They shall support me not impede ;)

**Comment by KamilSzczygiel** [comment]
> The "_D" stands for "Double" which means the " sign.

Maybe name the macro UNQUOTE_DOUBLE in that case?

> It is just above inside the VERBOSE if.

Let's pretend that I didn't ask that question (;

> In the long run, I planned to use "prinf" in DO_PRINT. But currently I have no Windows with MSYS arround to test, if printf is supported by the MSYS installation. With printf we can then add "\t".

Hmm... I'm hesitant to add another tool dependency, especially for something as trivial and unimportant (sorry...) as column alignment in short compilation log.

> Please can you test in a MSYS shell if "printf" is available.

It is available, but let's discuss a little more about adding it as another dependency.

> I know this from my company. There we have the rule to align even variable definitions at the beginning of a C function. So we use more spaces than required to be open for such a change, but sometimes I need to extend the spaces in all lines. On the other hand it is more readable and that's the reason why the company forces this rule.

I'd still prefer not to implement such rule here...

> I needed to write anything why I would like to change it, to be honest.

I know (; But please also aim for making/keeping the build system simple - that's my main concern with make and tup. The build systems are more complicated than I'd like them to be. The change you proposed (":=") is good and please go ahead with it - it doesn't complicate things.

> Most of the people using make don't know the difference, even the don't know ":=".

I knew the difference (;

**Comment by jasmin-j** [comment]
> Maybe name the macro UNQUOTE_DOUBLE in that case?

ACK

> Let's pretend that I didn't ask that question (;

What question you talk about?

> Hmm... I'm hesitant to add another tool dependency, especially for something as trivial and
> unimportant (sorry...) as column alignment in short compilation log.
> It is available, but let's discuss a little more about adding it as another dependency.

"printf" is part of the coreutils package and therefore available on every system which have this ported. There are commands like rm, mv, ls in this package. So it's no real added tool like kconfig-mconf. The latter is a real problem, because it is currently outdated and we should address this, too. I wrote you an [eMail] (http://sourceforge.net/p/distortos/mailman/message/34508072/) about it a week ago on the list, but might have missed out the part about a new version of kconfig-mconf.

> > I know this from my company. There we have the rule to align even variable definitions ...

> I'd still prefer not to implement such rule here...

I mentioned it only to explain why I asked. If you don't like it, it is very OK for me. In my old company we had an opposite rule ;) Having a rule is not always a good idea. There should be a general direction, but exceptions might be allowed, if they are appropriate.

> I know (; But please also aim for making/keeping the build system simple - that's my main concern
> with make and tup. The build systems are more complicated than I'd like them to be.

I don't think it is complicated for a user. There is a difference between a maintainer and the user. Even it might be more complicate for the person who is in charge, for the average user of distortos it is pretty simple and it looks good, too ;)
* It is straight forward:
```
make menuconfig or kconfig-mconf Kconfig
make configure [CONFIG_PATH=<...>] or configure.sh <...>
make or tup
```
* If only the OS library is required, this is a simple click and it is done.
* Before this project, I never heard about tup. This is a really good tool, which will hopefully evolve a little bit to get rid of some limitation, make doesn't have. I really consider it for my projects, if they get bigger.

The only really tricky part is the recursive include of the Rules.mk files. But on the other side, this makes it fast and maintainable. Imagine you would use autoconf/automake. This is even more complicated (although widely used).

You did an amazing job so far! There might be still edges and flaws with the re-usability of the make/tup files, but ... hey you wrote an OS! Now it is time to use it more widely and this will add requirements and improve all parts including the build process.

> I knew the difference (;

You really aren't "most people" ;) In my company a lot of my colleges know only very basic things of make. They complain about "$(aaa_$(strip bbb))" being too complicated to understand, especially if it is on the left side.

**Pull request closed without merging**
