### PR TITLE
Fixed shebang in STM32F4.ld.sh

### PR DESCRIPTION
**Pull request by jasmin-j**
Fixed shebang in STM32F4.ld.sh, too.

Signed-off-by: Jasmin Jessich <jasmin@anw.at>

### CODE REVIEW

**Comment by KamilSzczygiel** [comment]
Thanks!

**Comment by jasmin-j** [comment]
If you really want to write portable code for Windows, you shouldn't use "bash", but "sh".
I know there is MSYS and Cygwin, but there are people who doesn't like them because of the
DLL both of them use.
If there is no strong requirement using "bash", you should rewrite the scripts to use "/bin/sh".

**Comment by KamilSzczygiel** [comment]
You mean "rewrite" as "write from scratch because it won't work with sh", or just change the shebang at the top?

**Comment by jasmin-j** [comment]
I mean changing the shebang to "/bin/sh" and try running the script.
If you get errors correct them to simple Shell syntax if possible.
In really most cases shell scripts aren't Bash specific. I guess the scripts in distortos aren't.

**Comment by KamilSzczygiel** [comment]
done

**Comment by jasmin-j** [comment]
Fixed in pull request #6.

**Pull request merged**
