### PR TITLE
Debian compilation fix

### PR DESCRIPTION
**Pull request by gkostka**
Hi Kamil,

i discovered some issues with distortos compilation on my linux distro. Merge my branch if You like ;)

### CODE REVIEW

**Comment by KamilSzczygiel** [comment]
Hello Grzegorz!

Commit 1: wouldn't a change to shebang - as in pull request #9 - result in the same behavior? I'd actually prefer to just change the shebang (;

Commit 2: This is the same as in pull request #9 (; I actually like your pull request a bit more, because it follows the principle of "one commit == one logical change".

Please update the date of files in the header when you change them.

Final issue - why are we talking in English? <:

**Comment by jasmin-j** [comment]
> Commit 2: This is the same as in pull request #9 (; I actually like your pull request a bit more,
> because it follows the principle of "one commit == one logical change".

@gkostka:
Please change your pull request, because it is easier for you than for me to split it up.
I will close my pull request #9.

> Final issue - why are we talking in English? <:

May I ask: Why did you write distortos in English?
-> Because there are other people participating and it is a great idea, that all can understand
what's going on. So please keep discussions in a language, which most people are able to
understand.

**Comment by KamilSzczygiel** [comment]
> > Final issue - why are we talking in English? <:
> May I ask: Why did you write distortos in English?
> -> Because there are other people participating and it is a great idea, that
> all can understand what's going on. So please keep discussions in a
> language, which most people are able to understand.

It's just a small joke, as Grzegorz is also from Poland and we "know" each 
other from the elektroda.pl forum (;

**Comment by gkostka** [comment]
Done.

**Comment by KamilSzczygiel** [comment]
I see you removed the commit that fixed the execution of makeDistortosConfiguration.awk, so I fixed that myself just now (with the change to shebang). Could you please tell me whether it's working for you know?

**Comment by gkostka** [comment]
Yes, now it is working :)

**Pull request merged**
